/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import client.core.Connection;
import static client.gui.MixingPane.SELECTION_COLOR;
import java.awt.AWTEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author edmundophie
 */
public class FindPane extends javax.swing.JPanel implements WindowPane, MouseListener {
    private javax.swing.JPanel cards;
    private JLabel selectedLbl;
    private final Color selectionColor = Color.ORANGE;
    
    /**
     * Creates new form InventoryPane
     */
    public FindPane(javax.swing.JPanel cards) {
        this.cards = cards;
        initComponents();
        // Inventory Item
        philStoneLbl.setIcon(GrandQuest.philStoneImg);
        philStoneLbl.setHorizontalTextPosition(JLabel.CENTER);
        philStoneLbl.setVerticalTextPosition(JLabel.BOTTOM);
        philStoneLbl.addMouseListener(this);
        elixirLbl.setIcon(GrandQuest.elixirImg);
        elixirLbl.setHorizontalTextPosition(JLabel.CENTER);
        elixirLbl.setVerticalTextPosition(JLabel.BOTTOM);
        elixirLbl.addMouseListener(this);
        crystalLbl.setIcon(GrandQuest.crystalImg);
        crystalLbl.setHorizontalTextPosition(JLabel.CENTER);
        crystalLbl.setVerticalTextPosition(JLabel.BOTTOM);
        crystalLbl.addMouseListener(this);
        potionLbl.setIcon(GrandQuest.potionImg);
        potionLbl.setHorizontalTextPosition(JLabel.CENTER);
        potionLbl.setVerticalTextPosition(JLabel.BOTTOM);
        potionLbl.addMouseListener(this);
        incenseLbl.setIcon(GrandQuest.incenseImg);
        incenseLbl.setHorizontalTextPosition(JLabel.CENTER);
        incenseLbl.setVerticalTextPosition(JLabel.BOTTOM);
        incenseLbl.addMouseListener(this);
        gemsLbl.setIcon(GrandQuest.gemsImg);
        gemsLbl.setHorizontalTextPosition(JLabel.CENTER);
        gemsLbl.setVerticalTextPosition(JLabel.BOTTOM);
        gemsLbl.addMouseListener(this);
        honeyLbl.setIcon(GrandQuest.honeyImg);
        honeyLbl.setHorizontalTextPosition(JLabel.CENTER);
        honeyLbl.setVerticalTextPosition(JLabel.BOTTOM);
        honeyLbl.addMouseListener(this);
        herbsLbl.setIcon(GrandQuest.herbsImg);
        herbsLbl.setHorizontalTextPosition(JLabel.CENTER);
        herbsLbl.setVerticalTextPosition(JLabel.BOTTOM);
        herbsLbl.addMouseListener(this);
        clayLbl.setIcon(GrandQuest.clayImg);
        clayLbl.setHorizontalTextPosition(JLabel.CENTER);
        clayLbl.setVerticalTextPosition(JLabel.BOTTOM);
        clayLbl.addMouseListener(this);
        mineralLbl.setIcon(GrandQuest.mineralImg);
        mineralLbl.setHorizontalTextPosition(JLabel.CENTER);
        mineralLbl.setVerticalTextPosition(JLabel.BOTTOM);   
        mineralLbl.addMouseListener(this);
        
        selectedLbl=null;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        philStoneLbl = new javax.swing.JLabel();
        crystalLbl = new javax.swing.JLabel();
        elixirLbl = new javax.swing.JLabel();
        incenseLbl = new javax.swing.JLabel();
        potionLbl = new javax.swing.JLabel();
        honeyLbl = new javax.swing.JLabel();
        gemsLbl = new javax.swing.JLabel();
        clayLbl = new javax.swing.JLabel();
        mineralLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        herbsLbl = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        philStoneLbl.setText("0");
        add(philStoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        crystalLbl.setText("0");
        add(crystalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        elixirLbl.setText("0");
        add(elixirLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        incenseLbl.setText("0");
        add(incenseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        potionLbl.setText("0");
        add(potionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        honeyLbl.setText("0");
        add(honeyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        gemsLbl.setText("0");
        add(gemsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        clayLbl.setText("0");
        add(clayLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        mineralLbl.setText("0");
        add(mineralLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Level 4");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Level 1");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Level 2");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Level 3");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jButton2.setText("Find");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 110, 40));

        herbsLbl.setText("0");
        add(herbsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 70, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ((CardLayout) cards.getLayout()).show(cards, MainFrame.MAP);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Create request JSON
        JSONObject request = new JSONObject();
        request.put("method", "sendfind");
        request.put("token", GrandQuest.SESSION.getToken());
        request.put("item", getIdItem(selectedLbl));
        Connection conn = new Connection();
        JSONObject response = conn.sendToServer(request);
        System.out.println("resp: " + response);
        if(response.get("status").equals(GrandQuest.STATUS_OK)) {
            if(((JSONArray)response.get("offers")).size()==0) {  // No offer match
                JOptionPane.showMessageDialog(this, "There is no offer match the item", "OFFER NOT FOUND", JOptionPane.WARNING_MESSAGE);
                reloadContent();
            } else { // Offer found
                TradingPane.SEARCH_RESULT = (JSONArray) response.get("offers");
                GrandQuest.FRAME.getPane(MainFrame.TRADING).reloadContent();
                ((CardLayout) cards.getLayout()).show(cards, MainFrame.TRADING);
            }
        } else { // STATUS_ERROR
            JOptionPane.showMessageDialog(this, "Server return an error status", "OFFER ERROR", JOptionPane.ERROR_MESSAGE);
            reloadContent();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private int getIdItem(JLabel mixItemLbl) {
        if(mixItemLbl==honeyLbl){
            return 0;
        } else if(mixItemLbl==herbsLbl) {
            return 1;
        } else if(mixItemLbl==clayLbl) {
            return 2;
        } else if(mixItemLbl==mineralLbl) {
            return 3;
        } else if(mixItemLbl==potionLbl) {
            return 4;
        } else if(mixItemLbl==incenseLbl) {
            return 5;
        } else if(mixItemLbl==gemsLbl) {
            return 6;
        } else if(mixItemLbl==elixirLbl) {
            return 7;
        } else if(mixItemLbl==crystalLbl) {
            return 8;
        } 
       return 9999;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clayLbl;
    private javax.swing.JLabel crystalLbl;
    private javax.swing.JLabel elixirLbl;
    private javax.swing.JLabel gemsLbl;
    private javax.swing.JLabel herbsLbl;
    private javax.swing.JLabel honeyLbl;
    private javax.swing.JLabel incenseLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mineralLbl;
    private javax.swing.JLabel philStoneLbl;
    private javax.swing.JLabel potionLbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reloadContent() {
        // Create Request JSON
        JSONObject request = new JSONObject();
        request.put("method", "inventory");
        request.put("token", GrandQuest.SESSION.getToken());
        
        Connection conn = new Connection();
        JSONObject response = conn.sendToServer(request);
        if(response.get("status").equals(GrandQuest.STATUS_OK)) {
            updateInventory((JSONArray) response.get("inventory"));
        } else { // STATUS_ERROR
            JOptionPane.showMessageDialog(this, "Server return an error status on getting inventory.", "Error", JOptionPane.ERROR_MESSAGE);
        }     
//        if(selectedLbl!=null) {
//            selectedLbl.setOpaque(false);
//            selectedLbl.setBackground(selectionColor);
//        }
//        selectedLbl = null;
    }
    
    private void updateInventory(JSONArray itemsCount) {
        for(int i=0;i<itemsCount.size();++i)
            GrandQuest.SESSION.itemCount[i] = ((Long) itemsCount.get(i)).intValue();
        
        // Set item count label
        honeyLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[0]));
        herbsLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[1]));
        clayLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[2]));
        mineralLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[3]));
        potionLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[4]));
        incenseLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[5]));
        gemsLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[6]));
        elixirLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[7]));
        crystalLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[8]));
        philStoneLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[9]));
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        if(e.getSource()==honeyLbl || e.getSource()==herbsLbl || 
            e.getSource()==clayLbl || e.getSource()==mineralLbl || 
            e.getSource()==potionLbl || e.getSource()==incenseLbl || 
            e.getSource()==gemsLbl || e.getSource()==elixirLbl || 
            e.getSource()==crystalLbl) {
            if(selectedLbl!=null) {
                selectedLbl.setOpaque(false);
                selectedLbl.setBackground(null);
            }
            selectedLbl = (JLabel) e.getSource();
            selectedLbl.setOpaque(true);
            selectedLbl.setBackground(SELECTION_COLOR);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
}
