/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import client.core.Connection;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author edmundophie
 */
public class InventoryPane extends javax.swing.JPanel implements WindowPane {
    private javax.swing.JPanel cards;
    
    /**
     * Creates new form InventoryPane
     */
    public InventoryPane(javax.swing.JPanel cards) {
        this.cards = cards;
        initComponents();
        philStoneLbl.setIcon(GrandQuest.philStoneImg);
        philStoneLbl.setHorizontalTextPosition(JLabel.CENTER);
        philStoneLbl.setVerticalTextPosition(JLabel.BOTTOM);
        elixirLbl.setIcon(GrandQuest.elixirImg);
        elixirLbl.setHorizontalTextPosition(JLabel.CENTER);
        elixirLbl.setVerticalTextPosition(JLabel.BOTTOM);
        crystalLbl.setIcon(GrandQuest.crystalImg);
        crystalLbl.setHorizontalTextPosition(JLabel.CENTER);
        crystalLbl.setVerticalTextPosition(JLabel.BOTTOM);
        potionLbl.setIcon(GrandQuest.potionImg);
        potionLbl.setHorizontalTextPosition(JLabel.CENTER);
        potionLbl.setVerticalTextPosition(JLabel.BOTTOM);
        incenseLbl.setIcon(GrandQuest.incenseImg);
        incenseLbl.setHorizontalTextPosition(JLabel.CENTER);
        incenseLbl.setVerticalTextPosition(JLabel.BOTTOM);
        gemsLbl.setIcon(GrandQuest.gemsImg);
        gemsLbl.setHorizontalTextPosition(JLabel.CENTER);
        gemsLbl.setVerticalTextPosition(JLabel.BOTTOM);
        honeyLbl.setIcon(GrandQuest.honeyImg);
        honeyLbl.setHorizontalTextPosition(JLabel.CENTER);
        honeyLbl.setVerticalTextPosition(JLabel.BOTTOM);
        herbsLbl.setIcon(GrandQuest.herbsImg);
        herbsLbl.setHorizontalTextPosition(JLabel.CENTER);
        herbsLbl.setVerticalTextPosition(JLabel.BOTTOM);
        clayLbl.setIcon(GrandQuest.clayImg);
        clayLbl.setHorizontalTextPosition(JLabel.CENTER);
        clayLbl.setVerticalTextPosition(JLabel.BOTTOM);
        mineralLbl.setIcon(GrandQuest.mineralImg);
        mineralLbl.setHorizontalTextPosition(JLabel.CENTER);
        mineralLbl.setVerticalTextPosition(JLabel.BOTTOM);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        philStoneLbl = new javax.swing.JLabel();
        crystalLbl = new javax.swing.JLabel();
        elixirLbl = new javax.swing.JLabel();
        incenseLbl = new javax.swing.JLabel();
        potionLbl = new javax.swing.JLabel();
        honeyLbl = new javax.swing.JLabel();
        gemsLbl = new javax.swing.JLabel();
        clayLbl = new javax.swing.JLabel();
        mineralLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        herbsLbl = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        philStoneLbl.setText("0");
        add(philStoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        crystalLbl.setText("0");
        add(crystalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        elixirLbl.setText("0");
        add(elixirLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        incenseLbl.setText("0");
        add(incenseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        potionLbl.setText("0");
        add(potionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        honeyLbl.setText("0");
        add(honeyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        gemsLbl.setText("0");
        add(gemsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        clayLbl.setText("0");
        add(clayLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        mineralLbl.setText("0");
        add(mineralLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Level 4");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Level 1");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Level 2");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Level 3");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 110, 40));

        herbsLbl.setText("0");
        add(herbsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ((CardLayout) cards.getLayout()).show(cards, MainFrame.MAP);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clayLbl;
    private javax.swing.JLabel crystalLbl;
    private javax.swing.JLabel elixirLbl;
    private javax.swing.JLabel gemsLbl;
    private javax.swing.JLabel herbsLbl;
    private javax.swing.JLabel honeyLbl;
    private javax.swing.JLabel incenseLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mineralLbl;
    private javax.swing.JLabel philStoneLbl;
    private javax.swing.JLabel potionLbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reloadContent() {
        // Create Request JSON
        JSONObject request = new JSONObject();
        request.put("method", "inventory");
        request.put("token", GrandQuest.SESSION.getToken());
        
        Connection conn = new Connection();
        JSONObject response = conn.sendToServer(request);
        if(response.get("status").equals(GrandQuest.STATUS_OK)) {
            updateInventory((JSONArray) response.get("inventory"));
        } else { // STATUS_ERROR
            JOptionPane.showMessageDialog(this, "Server return an error status on getting inventory.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateInventory(JSONArray itemsCount) {
        for(int i=0;i<itemsCount.size();++i)
            GrandQuest.SESSION.itemCount[i] = ((Long) itemsCount.get(i)).intValue();
        
        // Set item count label
        honeyLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[0]));
        herbsLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[1]));
        clayLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[2]));
        mineralLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[3]));
        potionLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[4]));
        incenseLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[5]));
        gemsLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[6]));
        elixirLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[7]));
        crystalLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[8]));
        philStoneLbl.setText(String.valueOf(GrandQuest.SESSION.itemCount[9]));
    }
}
