/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author edmundophie
 */
public class MainFrame extends javax.swing.JFrame {
    public String title = "Grand Quest";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        // Setup frame
        this.setTitle(title);
        this.setPreferredSize(new Dimension(800, 600));
        initComponents();
        initIcon();
        findPane = new FindPane(cards);
        inventoryPane = new InventoryPane(cards);
        loginPane = new LoginPane(cards);
        mapPane = new MapPane(cards);
        mixingPane = new MixingPane(cards);
        offerPane = new OfferPane(cards);
        tradeboxPane = new TradeboxPane(cards);
        tradingPane = new TradingPane(cards);
        
        cards.add(loginPane, LOGIN);
        cards.add(mapPane, MAP);
        cards.add(inventoryPane, INVENTORY);
        cards.add(mixingPane, MIXING);
        cards.add(tradeboxPane, TRADEBOX);
        cards.add(offerPane, OFFER);
        cards.add(findPane, FIND);
        cards.add(tradingPane, TRADING);
        
        ((CardLayout) cards.getLayout()).show(cards, LOGIN);
    }

    private void initIcon() {
        try {
            GrandQuest.philStoneImg = new ImageIcon(ImageIO.read(new File(GrandQuest.PHILSTONE_FILE)));
            GrandQuest.elixirImg = new ImageIcon(ImageIO.read(new File(GrandQuest.ELIXIR_FILE)));
            GrandQuest.crystalImg = new ImageIcon(ImageIO.read(new File(GrandQuest.CRYSTAL_FILE)));
            GrandQuest.potionImg = new ImageIcon(ImageIO.read(new File(GrandQuest.POTION_FILE)));
            GrandQuest.incenseImg = new ImageIcon(ImageIO.read(new File(GrandQuest.INCENSE_FILE)));
            GrandQuest.gemsImg = new ImageIcon(ImageIO.read(new File(GrandQuest.GEMS_FILE)));
            GrandQuest.honeyImg = new ImageIcon(ImageIO.read(new File(GrandQuest.HONEY_FILE)));
            GrandQuest.herbsImg = new ImageIcon(ImageIO.read(new File(GrandQuest.HERBS_FILE)));
            GrandQuest.clayImg = new ImageIcon(ImageIO.read(new File(GrandQuest.CLAY_FILE)));
            GrandQuest.mineralImg = new ImageIcon(ImageIO.read(new File(GrandQuest.MINERAL_FILE)));
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }
    
    public WindowPane getPane(String paneName) {
        if(paneName == MAP) {
            return mapPane;
        } else if(paneName == INVENTORY) {
            return inventoryPane;
        } else if(paneName == MIXING) {
            return mixingPane;
        } else if(paneName == TRADEBOX) {
            return tradeboxPane;
        } else if(paneName == OFFER) {
            return offerPane;
        } else if(paneName == FIND) {
            return findPane;
        } else if(paneName == TRADING) {
            return tradingPane;
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        cards.setLayout(new java.awt.CardLayout());
        getContentPane().add(cards, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private final FindPane findPane;
    private final InventoryPane inventoryPane;
    private final LoginPane loginPane;
    private final MapPane mapPane;
    private final MixingPane mixingPane;
    private final OfferPane offerPane;
    private final TradeboxPane tradeboxPane;
    private final TradingPane tradingPane;
    
    public final static String LOGIN = "loginPane";
    public final static String MAP = "mapPane";
    public final static String INVENTORY = "inventoryPane";
    public final static String MIXING = "mixingPane";
    public final static String TRADEBOX = "tradeboxPane";
    public final static String OFFER = "offerPane";
    public final static String FIND = "findPane";
    public final static String TRADING = "tradingPane";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cards;
    // End of variables declaration//GEN-END:variables
}
